### ISSUE TITLE
Alternative Verfahren - AltPmtInf

### ISSUE THREAD

**Issue by buesche** [epsitec-sa/facture-qr#1]
Der Inhalt des Feldes [0] und [1] von AltPmtInf ist laut _Schweizer Implementation Guidelines QR-Rechnung_ als _Additional_ markiert, was heisst, dass das Feld nicht geliefert werden muss (aber kann).

![image](https://user-images.githubusercontent.com/3862409/60488979-8c5cb900-9ca3-11e9-9aeb-bbcf75335f7b.png)

Wenn ich eine Swiss-QR-Bill mit dem Validator validiere, heisst es aber, dass die beiden Felder existieren müssen:
![1](https://user-images.githubusercontent.com/3862409/60488796-2e2fd600-9ca3-11e9-8047-3edc2960d4d7.PNG)

Ich denke, dass dies ein Fehler im Validator ist. Oder wie habt ihr das verstanden?

**Comment by epsitec** [comment]
Nach unserem Verständnis der IGs sind die Felder optional (sie dürfen leer bleiben), müssen aber dementsprechend als leere Zeilen mitgeliefert werden. Ich frage bei SIX nach, um sicherzustellen, ob das auch so gemeint worden ist.

**Comment by buesche** [comment]
Ich bin mir ziemlich sicher, dass die Zeilenschaltung nicht geliefert werden muss: 
![image](https://user-images.githubusercontent.com/3862409/60513755-48d07200-9cd8-11e9-99c6-292b6df94647.png)

Wenn ich die genannte QR-Rechnung auf dem Validierungs-Portal der SIX validiere (https://validation.iso-payments.ch/gp/qrrechnung/validation), sind die QR-Daten auch valid. 

Aber besser nochmals nachfragen. Danke :-)

**Comment by epsitec** [comment]
Ich warte auf die Antwort von SIX und melde mich wieder.

**Comment by epsitec** [comment]
Hier die Antwort von Albert Apolloner (SIX)

> Optionale Elemente am Ende können entfallen, das ist richtig. Viele QR Libraries machen das auch „ungefragt“ und lassen Leerzeilen am Ende (inkl. des letzten `CR/LF` nach dem letzten befüllten Element) einfach weg.
>
> Das ist auch der Grund wieso wir das End of Payment Kennzeichen eingeführt haben. Damit ist zumindest die Zeilenanzahl bis zu diesem Kennzeichen immer garantiert.

**Comment by epsitec** [comment]
@QJonny will update the validator to allow for the absence of the empty lines.

**Comment by buesche** [comment]
Danke für das abklären und korrigieren des Validator.

**Comment by QJonny** [comment]
Fixed, will be available on next release :)

**Comment by epsitec** [comment]
@buesche der Validator ist nun korrigiert und die neue Version live.
